# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894a0c83adbeba44d943e8447e8ba8df0ce47e27b3da83627d71b2b438f03e4d000d2dbf5949c1c3de4fdf4c37cbafc1f058491bd56c854b44730c5065cf26f9

test:
  secret_key_base: 1c9d42b6bf2f9b14e1cdd67e642f6c60b56dde0b9e58e572cf9907e09621a34f1c9def3e8380a838769dcb1b0e7e912bad172fed1da5ce11fc688ea1cc7d514c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
